name: news4u
description: "A sample News application using clean architecture and bloc pattern."

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.2.2 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.6
  equatable: ^2.0.5
  dio: ^5.4.0
  shared_preferences: ^2.2.2
  flutter_bloc: ^8.1.3
  bloc: ^8.1.2
  bloc_concurrency: ^0.2.2
  bloc_test: ^9.1.5
  get_it: ^7.6.4

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.1
  mocktail: ^1.0.1

flutter:
  assets:
    - assets/n4u_logo.png
  uses-material-design: true